project:
  type: website

website:
  title: "(x)Ability Design Lab"
  site-url: "https://xability.github.io/"
  repo-url: "https://github.com/xability/xability.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



